name: publish
on:
  push:
    # tags:
    #   - v*
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    # if: ${{github.ref == 'refs/heads/master'}}
    outputs:
      package-name: ${{steps.package-name.outputs.package_name}}
    #   version: ${{steps.get-version.outputs.version}}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - run: npm install

      - name: generate changelog
        uses: fabernovel/github-changelog-generator-action@master
        with:
          # You can pass any parameters from https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options
          options: --token ${{ secrets.GITHUB_TOKEN }}

      # - name: get version
      #   id: get-version
      #   run: echo ::set-output name=version::${{GITHUB_REF/refs\/tags\/v/}}
      # - uses: vemel/update-changelog@0.0.1
      #   id: changelog
      #   with:
      #     version: ${{ steps.get-version.outputs.version }}

      - name: upload changelog
        if: ${{github.actor != 'nektos/act'}}
        uses: actions/upload-artifact@v2
        with:
            name: CHANGELOG.md
            path: CHANGELOG.md

      # - name: install vsce
      #   run: npm install -g vsce
      # - name: package an extension
      #   run: vsce package
      # - name: get package name
      #   id: package-name
      #   run: echo "::set-output name=package_name::$(ls | grep '^.*\.vsix$' | head -1)"
      # - name: upload package
      #   if: ${{github.actor != 'nektos/act'}}
      #   uses: actions/upload-artifact@v2
      #   with:
      #       name: ${{steps.package-name.outputs.package_name}}
      #       path: ${{steps.package-name.outputs.package_name}}
      # - name: publish package
      #   if: ${{github.actor != 'nektos/act'}}
      #   run: vsce publish -p ${{secrets.PAT}}
      # - name: create release
      #   if: ${{github.actor != 'nektos/act'}}
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     # body: ${{ steps.changelog.outputs.changelogs }}
      #     body-path: CHANGELOG.md
      #     draft: false
      #     # prerelease: ${{ steps.changelogs.outputs.release_type == 'prerelease' }}



  # release:
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   # if: ${{github.ref == 'refs/heads/master'}}
  #   env:
  #     package-name: ${{needs.build.outputs.package-name}}
  #   steps:
  #     - name: echo variables
  #       run: echo 'env.package-name ${{env.package-name}}; needs.build.outputs.package-name ${{needs.build.outputs.package-name}}'
  #     - name: download package
  #       if: ${{github.actor != 'nektos/act'}}
  #       uses: actions/download-artifact@v2
  #       with:
  #           name: ${{env.package-name}}

  #     # - name: create release (automatic)
  #     #   if: ${{github.actor != 'nektos/act'}}
  #     #   uses: marvinpinto/action-automatic-releases@latest
  #     #   with:
  #     #     repo_token: ${{ secrets.GITHUB_TOKEN }}
  #     #     automatic_release_tag: "latest"
  #     #     prerelease: false
  #     #     files: ${{env.package-name}}

  #     # - name: create changelog
  #     #   id: changelog
  #     #   uses: heineiuo/create-changelogs@master
